version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devUser@2024
      MYSQL_DATABASE: standby_db
      MYSQL_USER: devUser
      MYSQL_PASSWORD: devUser@2024
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: devUser
      POSTGRES_PASSWORD: devUser@2024
      POSTGRES_DB: standby_db
    ports:
      - "5432:5432"


