version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devUser@2024
      MYSQL_DATABASE: standby_db
      MYSQL_USER: devUser
      MYSQL_PASSWORD: devUser@2024
    ports:
      - "3306:3306"
    networks:
      - wp_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_db
    restart: always
    ports:
      - "80:80"
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge
